spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456qirui3
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true

logging:
  level:
    root: info
    com.scs: debug
  file:
    name: log/blog-dev.log