spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456qirui3
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.scs: info
  file:
    name: log/blog-pro.log